export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const CURRENT_USER_CART_REQUEST = "CURRENT_USER_CART_REQUEST";
export const CURRENT_USER_CART_SUCCESS = "CURRENT_USER_CART_SUCCESS";
export const CURRENT_USER_CART_FAIL = "CURRENT_USER_CART_FAIL";

export const CART_ITEM_DETAILS_REQUEST = "CART_ITEM_DETAILS_REQUEST";
export const CART_ITEM_DETAILS_SUCCESS = "CART_ITEM_DETAILS_SUCCESS";
export const CART_ITEM_DETAILS_FAIL = "CART_ITEM_DETAILS_FAIL";

export const CART_CHECKOUT_REQUEST = "CART_CHECKOUT_REQUEST";
export const CART_CHECKOUT_SUCCESS = "CART_CHECKOUT_SUCCESS";
export const CART_CHECKOUT_FAIL = "CART_CHECKOUT_SUCCESS";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";

export const CHECKOUT_UPI_REQUEST = "CHECKOUT_UPI_REQUEST";
export const CHECKOUT_UPI_SUCCESS = "CHECKOUT_UPI_REQUEST";
export const CHECKOUT_UPI_FAIL = "CHECKOUT_UPI_FAIL";