export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const CURRENT_USER_ORDERS_REQUEST = "CURRENT_USER_ORDERS";
export const CURRENT_USER_ORDERS_SUCCESS = "CURRENT_USER_oRDERS_SUCCESS";
export const CURRENT_USER_ORDERS_FAIL = "CURRENT_USER_ORDERS_FAIL"; 

export const GET_SINGLE_ORDER_REQUEST = "GET_SINGLE_ORDER_REQUEST";
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS";
export const GET_SINGLE_ORDER_FAIL = "GET_SINGLE_ORDER_FAIL";

export const UPI_ORDER_REQUEST = "UPI_ORDER_REQUEST";
export const UPI_ORDER_SUCCESS = "UPI_ORDER_SUCCESS";
export const UPI_ORDER_FAIL = "UPI_ORDER_FAIL";