export const GET_ALL_STORES_REQUEST = "GET_ALL_STORES_REQUEST";
export const GET_ALL_STORES_SUCCESS = "GET_ALL_STORES_SUCCESS";
export const GET_ALL_STORES_FAIL = "GET_ALL_STORES_FAIL";

export const CREATE_STORE_REQUEST = "CREATE_STORE_REQUEST";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const CREATE_STORE_FAIL = "CREATE_STORE_FAIL";